MODEA EQU 0X01

    ORG 0X00
    GOTO INICIO

    ORG 0X04

INT
    GOTO INT

INICIO
    BSF STATUS, RP0
    CLRF TRISB
    BCF STATUS, RP0
    BSF STATUS, RP0
    CLRF TRISD
    BCF STATUS, RP0
LOOP    
    MOVLW 0x01 
    MOVWF PORTD
    	
    MOVLW 0x3f 
    MOVWF PORTB
    MOVLW 0x06
    MOVWF PORTB
    MOVLW 0x5b
    MOVWF PORTB
    MOVLW 0x4f
    MOVWF PORTB
    MOVLW 0x66
    MOVWF PORTB
    MOVLW 0x6d
    MOVWF PORTB
    MOVLW 0x7d
    MOVWF PORTB
    MOVLW 0x07
    MOVWF PORTB
    MOVLW 0x7f
    MOVWF PORTB
    MOVLW 0x6f
    MOVWF PORTB
   
    MOVLW 0x02 
    MOVWF PORTD 

    
    MOVLW 0x06
    MOVWF PORTB
    MOVLW 0x5b
    MOVWF PORTB
    MOVLW 0x4f
    MOVWF PORTB
    MOVLW 0x66
    MOVWF PORTB
    MOVLW 0x6d
    MOVWF PORTB
    MOVLW 0x7d
    MOVWF PORTB
    MOVLW 0x07
    MOVWF PORTB
    MOVLW 0x7f
    MOVWF PORTB
    MOVLW 0x6f
    MOVWF PORTB
    
    MOVLW 0x04 
    MOVWF PORTD
    	
    MOVLW 0x3f 
    MOVWF PORTB
    MOVLW 0x06
    MOVWF PORTB
    MOVLW 0x5b
    MOVWF PORTB
    MOVLW 0x4f
    MOVWF PORTB
    MOVLW 0x66
    MOVWF PORTB
    MOVLW 0x6d
    MOVWF PORTB
    MOVLW 0x7d
    MOVWF PORTB
    MOVLW 0x07
    MOVWF PORTB
    MOVLW 0x7f
    MOVWF PORTB
    MOVLW 0x6f
    MOVWF PORTB
  
    MOVLW 0x08 
    MOVWF PORTD
    	
    MOVLW 0x3f 
    MOVWF PORTB
    MOVLW 0x06
    MOVWF PORTB
    MOVLW 0x5b
    MOVWF PORTB
    MOVLW 0x4f
    MOVWF PORTB
    MOVLW 0x66
    MOVWF PORTB
    MOVLW 0x6d
    MOVWF PORTB
    MOVLW 0x7d
    MOVWF PORTB
    MOVLW 0x07
    MOVWF PORTB
    MOVLW 0x7f
    MOVWF PORTB
    MOVLW 0x6f
    MOVWF PORTB
    GOTO LOOP